### ISSUE TITLE
Error while npm start

### ISSUE THREAD

**Issue by kapil019** [harryho/ng4crm#2] opened 2018-01-28 18:36 UTC
webpack: Compiled with warnings.

[at-loader] Checking finished with 8 errors
[at-loader] ./node_modules/ngx-progressbar/src/services/interceptor.provider.d.ts:5:55 
    TS2304: Cannot find name 'HttpInterceptor'. 

[at-loader] ./node_modules/ngx-progressbar/src/services/interceptor.provider.d.ts:8:20 
    TS2304: Cannot find name 'HttpRequest'. 

[at-loader] ./node_modules/ngx-progressbar/src/services/interceptor.provider.d.ts:8:44 
    TS2304: Cannot find name 'HttpHandler'. 

[at-loader] ./node_modules/ngx-progressbar/src/services/interceptor.provider.d.ts:8:69 
    TS2304: Cannot find name 'HttpEvent'. 

[at-loader] ./src/app/app.module.ts:8:49 
    TS2305: Module '"/var/www/html/kapil/ionic3/ng4crm/node_modules/ngx-progressbar/index"' has no exported member 'NgProgressService'. 

[at-loader] ./src/app/customer/customer.module.ts:4:49 
    TS2305: Module '"/var/www/html/kapil/ionic3/ng4crm/node_modules/ngx-progressbar/index"' has no exported member 'NgProgressService'. 

[at-loader] ./src/app/order/order.module.ts:4:49 
    TS2305: Module '"/var/www/html/kapil/ionic3/ng4crm/node_modules/ngx-progressbar/index"' has no exported member 'NgProgressService'. 

[at-loader] ./src/app/product/product.module.ts:4:49 
    TS2305: Module '"/var/www/html/kapil/ionic3/ng4crm/node_modules/ngx-progressbar/index"' has no exported member 'NgProgressService'.

**Comment by harryho** [comment] 2018-01-28 22:49
I can replicate the error on new ubuntu system. I guessed the problem is some redundant package hasn't been cleaned up. I will update you once it is fixed.

**Comment by harryho** [comment] 2018-01-29 09:32
@kapil019 : I cleaned up some packages and committed the changes. Please clone and try again. Please let me know if the issue has been fixed. By the way, this repository is not under development any more. There is another repo ng-md-app as replacement for Angular 5.

**Comment by harryho** [comment] 2018-01-30 22:54
@kapil019 : I closed the issue. If your problem is not solved, please feel free to re-open it.

**Closed as completed** 2018-01-30 22:54 UTC
Labels: bug

**Comment by kapil019** [comment] 2018-01-31 07:07
Thanks @harryho Now this is working fine.

**Comment by stenioanibal** [comment] 2018-04-09 12:42
Hello there! I have same problem of @kapil019 but, i remove all packages and run again the command `npm install` but, still not working. 

My versions:

```"@angular/common": "4.1.0",
"@angular/compiler": "4.1.0",
"@angular/compiler-cli": "4.1.0",
"@angular/core": "4.1.0",
"@angular/forms": "4.1.0",
"@angular/http": "4.1.0",
"@angular/platform-browser": "4.1.0",
"@angular/platform-browser-dynamic": "4.1.0",
"@ionic-native/app-availability": "^3.12.1",
"@ionic-native/core": "^3.6.1",
"@ionic-native/diagnostic": "^3.7.0",
"@ionic-native/file": "^3.6.1",
"@ionic-native/in-app-browser": "^3.7.0",
"@ionic-native/launch-navigator": "^3.7.0",
"@ionic-native/network": "^3.7.0",
"@ionic-native/social-sharing": "^3.7.0",
"@ionic-native/splash-screen": "3.4.2",
"@ionic-native/status-bar": "3.4.2",
"@ionic/storage": "2.0.1"
```

What suggest me to try @harryho ?

**Comment by stenioanibal** [comment] 2018-04-09 12:53
My errors:

```
typescript: node_modules/ngx-progressbar/src/services/interceptor.provider.d.ts, line: 5 
Cannot find name 'HttpInterceptor'. 

L4:  import 'rxjs/add/operator/finally';
L5:  export declare class NgProgressInterceptor implements HttpInterceptor {
L6:  ngProgress: NgProgress;

typescript: node_modules/ngx-progressbar/src/services/interceptor.provider.d.ts, line: 8 
Cannot find name 'HttpRequest'. 

L7:  constructor(ngProgress: NgProgress);
L8:  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>>;

[09:36:08]  typescript: node_modules/ngx-progressbar/src/services/interceptor.provider.d.ts, line: 8 
Cannot find name 'HttpHandler'. 

L7:  constructor(ngProgress: NgProgress);
L8:  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>>;

typescript: node_modules/ngx-progressbar/src/services/interceptor.provider.d.ts, line: 8 
Cannot find name 'HttpEvent'. 

L7:  constructor(ngProgress: NgProgress);
L8:  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>>;
```

**Comment by harryho** [comment] 2018-04-09 23:46
@stenioanibal : hi, there, I would suggest you to ask ionic team about this question or just simply use ionic's template. My experience for ionic still stayed at version 1. It seems packages used in your project are a bit old comparing with ionic's latest template. One thing you can try is to remove NgProgress from the project and see if it works or not. good luck.

**Comment by stenioanibal** [comment] 2018-04-10 15:48
I fix this problem updating my project packages. In my case, some package has broken in update/install and, this cause my problem.

Recommended solution:

- Check packages version using `npm outdated`
- Update your packages to latest or reccomended version;

Be attention to ProgressBar Version. This is the cause of my problem. In most cases, i see peoples running `npm install angular-progress-bar@latest --save` without see more about this. The package to install must be contains a version compatible with your application (Ionic, Angular...).

Now, my packages is:

```
"@angular/common": "5.2.9",
"@angular/compiler": "5.2.9",
"@angular/compiler-cli": "5.2.9",
"@angular/core": "5.2.9",
"@angular/forms": "5.2.9",
"@angular/http": "5.2.9",
"@angular/platform-browser": "5.2.9",
"@angular/platform-browser-dynamic": "5.2.9",
"@ionic-native/app-availability": "^4.7.0",
"@ionic-native/call-number": "^4.7.0",
"@ionic-native/core": "^4.7.0",
"@ionic-native/diagnostic": "^4.7.0",
"@ionic-native/file": "^4.7.0",
"@ionic-native/in-app-browser": "^4.7.0",
"@ionic-native/launch-navigator": "^4.7.0",
"@ionic-native/network": "^4.7.0",
"@ionic-native/social-sharing": "^4.7.0",
"@ionic-native/splash-screen": "4.7.0",
"@ionic-native/status-bar": "4.7.0" [...]
```

In my case, i prefered upgrade Ionic and another packages to latest version, but, an package version alignment would solve this problem.

PS 1: Remember, in relative latest Angular, `Http` is deprecated! See more in https://angular.io/api/http/Http
